### ISSUE TITLE
editer won't make new levels when extracted from ZIP File

### ISSUE THREAD

**Issue by BlusterBong** [donnaken15/Bit.Trip_Editor#1]
every time i extract the files from the zip and try to make a level, it keeps making an error: 

> ERROR IN ACTION NUMBER 1 OF DRAW EVENT FOR LEVELEDITOR_BEAT: TRYING TO EXECUTE NONE-EXISTING FILE. CASTER ERROR: HANDLER NOT FOUND

**Comment by donnaken15** [comment]
Whoops, the error is that it's trying to execute a file of code, because usually I edit the code in real time by using an external notepad. The GameMaker file appears to fix it but I guess I forgot to recompile it. Program is updated so it should work now. Level editor is still kind of broken with the textboxes and updating the timeline, but it still somewhat does what it's supposed to.
